In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

import plotly.express as px
from plotly.subplots import make_subplots
import plotly.graph_objects as go
import plotly.io as pio

import warnings
warnings.filterwarnings('ignore') 

# Set global visualization styles
pio.templates.default = "plotly_white"

#loading the data
df = pd.read_csv('pubg-weapon-stats.csv')

# PUBG wepon stats  
## Exploratory Data Analysis
This analysis aims to give details about weapon and bullets type in the PUBG game 


- How do weapon classes differ in performance metrics?
- What role does bullet type play in determining damage efficiency?
- Which features most strongly explain lethality?

### Dataset Overview

Dataset display and info

In [2]:
df.head()

,Weapon Name,Weapon Type,Bullet Type,Damage,Magazine Capacity,Range,Bullet Speed,Rate of Fire,Shots to Kill (Chest),Shots to Kill (Head),Damage Per Second,Fire Mode,BDMG_0,BDMG_1,BDMG_2,BDMG_3,HDMG_0,HDMG_1,HDMG_2,HDMG_3
0,Groza,Assault Rifle,7.62,49,30,400.0,715.0,0.080,4,2,612.0,"Single, Automatic, Burst",47.0,34.3,29.4,22.0,115.1,80.6,69.0,51.8
1,AKM,Assault Rifle,7.62,49,30,400.0,710.0,0.010,4,2,490.0,"Single, Automatic",47.0,34.3,29.4,22.0,115.1,80.6,69.0,51.8
2,M762,Assault Rifle,7.62,47,30,400.0,715.0,0.086,4,2,547.0,"Single, Automatic, Burst",46.0,32.9,28.2,21.1,110.4,77.3,66.2,49.7
3,MK47 Mutant,Assault Rifle,7.62,49,30,500.0,715.0,0.010,4,2,490.0,"Single, Burst",49.0,34.3,29.4,22.0,115.1,80.6,69.0,51.8
4,AUG A3,Assault Rifle,5.56,43,30,600.0,880.0,0.086,4,2,502.0,"Single, Automatic",41.0,30.1,25.8,19.3,101.0,70.7,60.6,45.4

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44 entries, 0 to 43
Data columns (total 20 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Weapon Name            44 non-null     object
 1   Weapon Type            44 non-null     object
 2   Bullet Type            38 non-null     float64
 3   Damage                 44 non-null     int64
 4   Magazine Capacity      44 non-null     int64
 5   Range                  38 non-null     float64
 6   Bullet Speed           36 non-null     float64
 7   Rate of Fire           44 non-null     float64
 8   Shots to Kill (Chest)  44 non-null     int64
 9   Shots to Kill (Head)   44 non-null     int64
 10  Damage Per Second      44 non-null     float64
 11  Fire Mode              44 non-null     object
 12  BDMG_0                 37 non-null     float64
 13  BDMG_1                 37 non-null     float64
 14  BDMG_2                 37 non-null     float64
 15  BDMG_3                 37 non-null     float64
 16  HDMG_0                 37 non-null     float64
 17  HDMG_1                 37 non-null     float64
 18  HDMG_2                 37 non-null     float64
 19  HDMG_3                 37 non-null     float64
dtypes: float64(13), int64(4), object(3)
memory usage: 7.0+ KB

In [4]:
df.describe()

,Bullet Type,Damage,Magazine Capacity,Range,Bullet Speed,Rate of Fire,Shots to Kill (Chest),Shots to Kill (Head),Damage Per Second,BDMG_0,BDMG_1,BDMG_2,BDMG_3,HDMG_0,HDMG_1,HDMG_2,HDMG_3
count,38.000000,44.000000,44.000000,38.000000,36.000000,44.000000,44.000000,44.000000,44.000000,37.000000,37.000000,37.00000,37.000000,37.000000,37.000000,37.000000,37.000000
mean,6.747632,63.340909,18.431818,403.552632,615.777778,0.388670,3.840909,2.136364,394.102500,68.081081,47.929730,41.02973,30.762162,125.756757,88.024324,75.418919,56.554054
std,3.336421,47.134613,18.421925,297.886492,256.455077,0.712255,1.829261,0.851562,230.785698,57.379254,40.074853,34.22249,25.699852,66.445937,46.555728,39.888009,29.872717
min,0.300000,18.000000,1.000000,25.000000,250.000000,0.010000,1.000000,1.000000,28.000000,22.400000,15.700000,13.40000,10.100000,44.900000,31.400000,26.900000,20.200000
25%,5.560000,41.000000,5.000000,52.500000,350.000000,0.063375,3.000000,2.000000,199.377500,41.000000,30.100000,25.80000,19.300000,96.300000,67.400000,57.800000,43.300000
50%,7.620000,48.500000,12.500000,400.000000,715.000000,0.091000,4.000000,2.000000,463.000000,47.000000,33.800000,28.90000,21.700000,109.600000,76.700000,65.700000,49.300000
75%,9.000000,60.250000,30.000000,600.000000,859.750000,0.347500,4.250000,2.250000,509.000000,60.900000,42.600000,36.50000,27.400000,136.300000,95.400000,81.700000,61.300000
max,12.000000,216.000000,100.000000,900.000000,990.000000,3.800000,10.000000,4.000000,1080.000000,282.600000,198.000000,169.20000,126.900000,312.300000,218.700000,187.200000,140.400000

In [5]:
print("Nulls:")
df.isnull().sum().sort_values(ascending=False)

Nulls:

Bullet Speed             8
HDMG_0                   7
HDMG_2                   7
HDMG_1                   7
HDMG_3                   7
BDMG_2                   7
BDMG_1                   7
BDMG_0                   7
BDMG_3                   7
Range                    6
Bullet Type              6
Weapon Name              0
Damage                   0
Weapon Type              0
Fire Mode                0
Damage Per Second        0
Rate of Fire             0
Magazine Capacity        0
Shots to Kill (Head)     0
Shots to Kill (Chest)    0
dtype: int64

In [6]:
print('duplicate rows =', df.duplicated().sum())

duplicate rows = 0

In [7]:
df["Fire Mode"].value_counts().reset_index()

                  Fire Mode  count
0                 Automatic     17
1                    Single     10
2         Single, Automatic     10
3  Single, Automatic, Burst      5
4             Single, Burst      2

In [8]:
df["Weapon Name"].value_counts().reset_index()

    Weapon Name  count
0         Groza      1
1           AKM      1
2          M762      1
3   MK47 Mutant      1
4        AUG A3      1
5        SCAR-L      1
6          M416      1
7         M16A4      1
8          G36C      1
9           OBZ      1
10         M249      1
11        DP-28      1
12       Vector      1
13          Uzi      1
14     PP-Bizon      1
15         MP5K      1
16     Thompson      1
17        UMP45      1
18         S686      1
19        S1897      1
20         S12K      1
21         MK14      1
22          SLR      1
23          SKS      1
24          QBU      1
25       Mini14      1
26          VSS      1
27          AWM      1
28          M24      1
29        Kar98      1
30        Win94      1
31    Sawed-Off      1
32        R1895      1
33          R45      1
34        P1911      1
35          P92      1
36         P18C      1
37     Skorpion      1
38     Crossbow      1
39          Pan      1
40      Crowbar      1
41       Sickle      1
42      Machete      1
43        Punch      1

In [9]:
is_NaN = df.isnull()
row_has_NaN = is_NaN.any(axis=1)

print("Rows with null values (NaN):")
df[row_has_NaN]

Rows with null values (NaN):

,Weapon Name,Weapon Type,Bullet Type,Damage,Magazine Capacity,Range,Bullet Speed,Rate of Fire,Shots to Kill (Chest),Shots to Kill (Head),Damage Per Second,Fire Mode,BDMG_0,BDMG_1,BDMG_2,BDMG_3,HDMG_0,HDMG_1,HDMG_2,HDMG_3
31,Sawed-Off,Pistol,12.00,160,2,25.0,NaN,0.25,2,1,640.0,Automatic,159.2,111.2,95.2,71.2,238.4,167.2,143.2,107.2
33,R45,Pistol,0.45,55,6,25.0,NaN,0.25,4,2,220.0,Automatic,54.8,38.3,32.8,24.6,109.6,76.7,65.7,49.3
37,Skorpion,Pistol,9.00,22,20,60.0,400.0,0.07,8,4,312.0,Automatic,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,Crossbow,Other,NaN,106,1,NaN,NaN,3.80,2,1,28.0,Single,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,Pan,Melee,NaN,80,1,NaN,NaN,0.75,3,1,107.0,Single,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,Crowbar,Melee,NaN,60,1,NaN,NaN,0.75,3,2,80.0,Single,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,Sickle,Melee,NaN,60,1,NaN,NaN,0.75,3,2,80.0,Single,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,Machete,Melee,NaN,60,1,NaN,NaN,0.75,3,2,80.0,Single,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,Punch,Melee,NaN,18,1,NaN,NaN,0.33,10,4,55.0,Single,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Some NaNs are logic (the No Ammu).. 

I checked the game app and online for the missing values

------------------------------------------------

## Dataset Overview

The dataset comprises 44 observations and 20 variables, representing weapon characteristics.

* **Critical Issues:**
    * **Missing Values:** Bullet Type, Range, and Damage profiles.
    * **Redundancy:** Derived variables may overlap.
    * **Encoding:** *Bullet Type* is incorrectly numerical. *Fire mode* has multiple enteries 

*Note*: Technical definitions, units, and calculations are currently unavailable, which may impact the precision of result interpretations.

**Handling Missing data strategy**:

Most of missing values are structurally dependent on weapon type (e.g., non-firearm weapons lack ammunition-related attributes). Other missing values were cross-validated using external domain sources. This preserves dataset completeness while avoiding bias introduced by listwise deletion, which would disproportionately remove specific weapon categories.

------------------------------

### Data Cleaning

In [10]:
print("Unique values in Bullet types column:")
df['Bullet Type'].unique()

Unique values in Bullet types column:

array([ 7.62,  5.56,  9.  ,  0.45, 12.  ,  0.3 ,   nan])

In [11]:
# Bullet Type to categorical
df['Bullet Type'] = df['Bullet Type'].astype('object')
bulletmap = {
    5.56: '5.56mm',
    7.62: '7.62mm',
    9.0: '9mm',
    0.45: '.45 ACP',
    12: '12 Gauge',
    0.3: '.300 Magnum'
}
# Replace numeric ammo with labels
df['Bullet Type'] = df['Bullet Type'].replace(bulletmap)

# Fill missing bullet types
df['Bullet Type'] = df['Bullet Type'].fillna('No Ammo').astype('category')

### Handling NaN

Instead of removing observations with missing values, a domain-informed imputation strategy was adopted:

- Weapons were categorised into firearm vs non-firearm

In [12]:
def classify_weapon(row):
    if row['Bullet Type'] == 'No Ammo':
        return 'Non-Firearm'
    else:
        return 'Firearm'

df['Weapon Class'] = df.apply(classify_weapon, axis=1)

- Missing numerical values were imputed using verified external references

- Sawed-Off, https://pubg.fandom.com/wiki/Sawed-off (**Bullet speed : 330**)    
- R45, https://pubg.fandom.com/wiki/R45 (**Bullet speed : 330**)

- Skorpion, https://pubg.fandom.com/wiki/Skorpion
  
| Level | BDMG (Body) | HDMG (Head) |
| :--- | :--- | :--- |
| Level 0 | 22.0 | 44.0 |
| Level 1 | 15.40 | 30.80 |
| Level 2 | 13.20 | 26.40 |
| Level 3 | 9.90 | 19.80 |

In [13]:

# Bullet speed (m/s)
df.loc[df['Weapon Name'] == 'Sawed-Off', 'Bullet Speed'] = 330
df.loc[df['Weapon Name'] == 'R45', 'Bullet Speed'] = 330

# Skorpion body damage
df.loc[df['Weapon Name'] == 'Skorpion', ['BDMG_0','BDMG_1','BDMG_2','BDMG_3']] = [22.0, 15.40, 13.20, 9.90]

# Skorpion head damage
df.loc[df['Weapon Name'] == 'Skorpion', ['HDMG_0','HDMG_1','HDMG_2','HDMG_3']] = [44.0, 30.80, 26.40, 19.80]

### Fire Mode handling

In [14]:
fire_modes = df['Fire Mode'].str.split(', ')

from sklearn.preprocessing import MultiLabelBinarizer

mlb = MultiLabelBinarizer()
fire_mode_dummies = pd.DataFrame(
    mlb.fit_transform(fire_modes),
    columns=mlb.classes_,
    index=df.index
)

# Merge back
df = pd.concat([df, fire_mode_dummies], axis=1)

df['num_fire_modes'] = fire_modes.apply(len)

Adding features sutainability

In [15]:
df['Damage_per_mag'] = df['Damage'] * df['Magazine Capacity']
df['Kills_per_mag'] = df['Magazine Capacity'] / df['Shots to Kill (Chest)']

Time to Kill (TTK) ?

In [16]:
df['TTK_chest'] = (df['Shots to Kill (Chest)'] - 1) * df['Rate of Fire']

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 44 entries, 0 to 43
Data columns (total 28 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Weapon Name            44 non-null     object
 1   Weapon Type            44 non-null     object
 2   Bullet Type            44 non-null     category
 3   Damage                 44 non-null     int64
 4   Magazine Capacity      44 non-null     int64
 5   Range                  38 non-null     float64
 6   Bullet Speed           38 non-null     float64
 7   Rate of Fire           44 non-null     float64
 8   Shots to Kill (Chest)  44 non-null     int64
 9   Shots to Kill (Head)   44 non-null     int64
 10  Damage Per Second      44 non-null     float64
 11  Fire Mode              44 non-null     object
 12  BDMG_0                 38 non-null     float64
 13  BDMG_1                 38 non-null     float64
 14  BDMG_2                 38 non-null     float64
 15  BDMG_3                 38 non-null     float64
 16  HDMG_0                 38 non-null     float64
 17  HDMG_1                 38 non-null     float64
 18  HDMG_2                 38 non-null     float64
 19  HDMG_3                 38 non-null     float64
 20  Weapon Class           44 non-null     object
 21  Automatic              44 non-null     int64
 22  Burst                  44 non-null     int64
 23  Single                 44 non-null     int64
 24  num_fire_modes         44 non-null     int64
 25  Damage_per_mag         44 non-null     int64
 26  Kills_per_mag          44 non-null     float64
 27  TTK_chest              44 non-null     float64
dtypes: category(1), float64(14), int64(9), object(4)
memory usage: 9.8+ KB

In [18]:
df.head()

,Weapon Name,Weapon Type,Bullet Type,Damage,Magazine Capacity,Range,Bullet Speed,Rate of Fire,Shots to Kill (Chest),Shots to Kill (Head),...,HDMG_2,HDMG_3,Weapon Class,Automatic,Burst,Single,num_fire_modes,Damage_per_mag,Kills_per_mag,TTK_chest
0,Groza,Assault Rifle,7.62mm,49,30,400.0,715.0,0.080,4,2,...,69.0,51.8,Firearm,1,1,1,3,1470,7.5,0.240
1,AKM,Assault Rifle,7.62mm,49,30,400.0,710.0,0.010,4,2,...,69.0,51.8,Firearm,1,0,1,2,1470,7.5,0.030
2,M762,Assault Rifle,7.62mm,47,30,400.0,715.0,0.086,4,2,...,66.2,49.7,Firearm,1,1,1,3,1410,7.5,0.258
3,MK47 Mutant,Assault Rifle,7.62mm,49,30,500.0,715.0,0.010,4,2,...,69.0,51.8,Firearm,0,1,1,2,1470,7.5,0.030
4,AUG A3,Assault Rifle,5.56mm,43,30,600.0,880.0,0.086,4,2,...,60.6,45.4,Firearm,1,0,1,2,1290,7.5,0.258

In [19]:
# df firearms

ammu = df[df['Weapon Class'] == 'Firearm']
ammu.info()

<class 'pandas.core.frame.DataFrame'>
Index: 38 entries, 0 to 37
Data columns (total 28 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Weapon Name            38 non-null     object
 1   Weapon Type            38 non-null     object
 2   Bullet Type            38 non-null     category
 3   Damage                 38 non-null     int64
 4   Magazine Capacity      38 non-null     int64
 5   Range                  38 non-null     float64
 6   Bullet Speed           38 non-null     float64
 7   Rate of Fire           38 non-null     float64
 8   Shots to Kill (Chest)  38 non-null     int64
 9   Shots to Kill (Head)   38 non-null     int64
 10  Damage Per Second      38 non-null     float64
 11  Fire Mode              38 non-null     object
 12  BDMG_0                 38 non-null     float64
 13  BDMG_1                 38 non-null     float64
 14  BDMG_2                 38 non-null     float64
 15  BDMG_3                 38 non-null     float64
 16  HDMG_0                 38 non-null     float64
 17  HDMG_1                 38 non-null     float64
 18  HDMG_2                 38 non-null     float64
 19  HDMG_3                 38 non-null     float64
 20  Weapon Class           38 non-null     object
 21  Automatic              38 non-null     int64
 22  Burst                  38 non-null     int64
 23  Single                 38 non-null     int64
 24  num_fire_modes         38 non-null     int64
 25  Damage_per_mag         38 non-null     int64
 26  Kills_per_mag          38 non-null     float64
 27  TTK_chest              38 non-null     float64
dtypes: category(1), float64(14), int64(9), object(4)
memory usage: 8.7+ KB

## EDA


#### Univariate Analysis

In [20]:
corr = df.select_dtypes(include=np.number).corr()

corr

,Damage,Magazine Capacity,Range,Bullet Speed,Rate of Fire,Shots to Kill (Chest),Shots to Kill (Head),Damage Per Second,BDMG_0,BDMG_1,...,HDMG_1,HDMG_2,HDMG_3,Automatic,Burst,Single,num_fire_modes,Damage_per_mag,Kills_per_mag,TTK_chest
Damage,1.000000,-0.372455,-0.236638,-0.173286,0.298839,-0.694160,-0.685451,0.222047,0.967694,0.967883,...,0.891304,0.891151,0.890880,-0.044803,-0.203212,-0.284693,-0.337124,-0.128640,-0.179025,0.007982
Magazine Capacity,-0.372455,1.000000,0.064416,0.245086,-0.382378,0.262949,0.242246,0.367258,-0.420449,-0.418300,...,-0.435101,-0.435127,-0.435651,0.378800,0.221702,0.052134,0.398318,0.948973,0.958115,-0.409668
Range,-0.236638,0.064416,1.000000,0.849803,0.306776,-0.332171,-0.369519,-0.185544,-0.187545,-0.185327,...,0.107281,0.107638,0.108604,-0.436705,-0.086574,0.355680,-0.022402,0.101376,0.158841,0.196832
Bullet Speed,-0.173286,0.245086,0.849803,1.000000,0.159270,-0.279396,-0.399538,-0.052436,-0.150126,-0.144553,...,0.117679,0.117833,0.118560,-0.335091,-0.074798,0.287778,-0.011369,0.321119,0.370149,0.062530
Rate of Fire,0.298839,-0.382378,0.306776,0.159270,1.000000,-0.374867,-0.467491,-0.608165,0.366993,0.364848,...,0.567593,0.567712,0.569085,-0.625895,-0.205018,0.261409,-0.327789,-0.324043,-0.333632,0.827740
Shots to Kill (Chest),-0.694160,0.262949,-0.332171,-0.279396,-0.374867,1.000000,0.924938,-0.076972,-0.734111,-0.735119,...,-0.844628,-0.844661,-0.845213,0.171883,0.141349,0.085060,0.245592,0.039376,0.044158,0.038563
Shots to Kill (Head),-0.685451,0.242246,-0.369519,-0.399538,-0.467491,0.924938,1.000000,0.015429,-0.683145,-0.686008,...,-0.835945,-0.835821,-0.836574,0.281053,0.150979,0.017642,0.273551,0.001926,0.017777,-0.132198
Damage Per Second,0.222047,0.367258,-0.185544,-0.052436,-0.608165,-0.076972,0.015429,1.000000,0.240264,0.243663,...,0.045248,0.044587,0.044641,0.698141,0.219866,-0.282691,0.367225,0.413473,0.407985,-0.766603
BDMG_0,0.967694,-0.420449,-0.187545,-0.150126,0.366993,-0.734111,-0.683145,0.240264,1.000000,0.999902,...,0.841516,0.841353,0.841671,-0.114644,-0.217002,-0.282354,-0.374050,-0.153544,-0.204236,0.046779
BDMG_1,0.967883,-0.418300,-0.185327,-0.144553,0.364848,-0.735119,-0.686008,0.243663,0.999902,1.000000,...,0.841760,0.841596,0.841912,-0.111609,-0.217212,-0.276715,-0.368672,-0.150700,-0.201380,0.044070
BDMG_2,0.967672,-0.417928,-0.184291,-0.143771,0.365834,-0.735616,-0.686740,0.242400,0.999902,0.999996,...,0.841975,0.841813,0.842126,-0.112347,-0.217314,-0.276303,-0.368818,-0.150089,-0.200812,0.044919
BDMG_3,0.967887,-0.418435,-0.184393,-0.143919,0.366104,-0.735480,-0.686414,0.242967,0.999908,0.999998,...,0.842385,0.842221,0.842540,-0.112447,-0.217596,-0.276571,-0.369210,-0.150776,-0.201446,0.045255
HDMG_0,0.891391,-0.435305,0.107683,0.117851,0.567905,-0.844988,-0.836099,0.045248,0.841951,0.842194,...,0.999998,0.999997,0.999996,-0.324254,-0.245096,-0.161630,-0.412389,-0.166851,-0.211331,0.231756
HDMG_1,0.891304,-0.435101,0.107281,0.117679,0.567593,-0.844628,-0.835945,0.045248,0.841516,0.841760,...,1.000000,0.999998,0.999994,-0.323904,-0.244970,-0.161748,-0.412223,-0.166708,-0.211249,0.231492
HDMG_2,0.891151,-0.435127,0.107638,0.117833,0.567712,-0.844661,-0.835821,0.044587,0.841353,0.841596,...,0.999998,1.000000,0.999988,-0.324004,-0.245086,-0.161557,-0.412205,-0.166756,-0.211236,0.231450
HDMG_3,0.890880,-0.435651,0.108604,0.118560,0.569085,-0.845213,-0.836574,0.044641,0.841671,0.841912,...,0.999994,0.999988,1.000000,-0.325454,-0.245100,-0.160968,-0.412544,-0.167294,-0.211723,0.233222
Automatic,-0.044803,0.378800,-0.436705,-0.335091,-0.625895,0.171883,0.281053,0.698141,-0.114644,-0.111609,...,-0.323904,-0.324004,-0.325454,1.000000,-0.012684,-0.485913,0.295468,0.358024,0.355602,-0.710230
Burst,-0.203212,0.221702,-0.086574,-0.074798,-0.205018,0.141349,0.150979,0.219866,-0.217002,-0.217212,...,-0.244970,-0.245086,-0.245100,-0.012684,1.000000,0.345136,0.764515,0.178754,0.173038,-0.225229
Single,-0.284693,0.052134,0.355680,0.287778,0.261409,0.085060,0.017642,-0.282691,-0.282354,-0.276715,...,-0.161748,-0.161557,-0.160968,-0.485913,0.345136,1.000000,0.574287,-0.033098,-0.021389,0.334213
num_fire_modes,-0.337124,0.398318,-0.022402,-0.011369,-0.327789,0.245592,0.273551,0.367225,-0.374050,-0.368672,...,-0.412223,-0.412205,-0.412544,0.295468,0.764515,0.574287,1.000000,0.302114,0.305779,-0.341544
Damage_per_mag,-0.128640,0.948973,0.101376,0.321119,-0.324043,0.039376,0.001926,0.413473,-0.153544,-0.150700,...,-0.166708,-0.166756,-0.167294,0.358024,0.178754,-0.033098,0.302114,1.000000,0.991857,-0.427003
Kills_per_mag,-0.179025,0.958115,0.158841,0.370149,-0.333632,0.044158,0.017777,0.407985,-0.204236,-0.201380,...,-0.211249,-0.211236,-0.211723,0.355602,0.173038,-0.021389,0.305779,0.991857,1.000000,-0.436299
TTK_chest,0.007982,-0.409668,0.196832,0.062530,0.827740,0.038563,-0.132198,-0.766603,0.046779,0.044070,...,0.231492,0.231450,0.233222,-0.710230,-0.225229,0.334213,-0.341544,-0.427003,-0.436299,1.000000

- Weapon

In [21]:
px.histogram(df, x='Weapon Type', title='Weapon Type Distribution')

Assault rifles dominate the dataset, reflecting their central role in gameplay meta.

- Bullet Types

In [22]:
px.pie(
    df,
    names='Bullet Type',
    title='Weapon Distribution by Ammo Type'
)

7.62mm bullets is the most common ammunation used

- Damage per weopon and bullet types

In [23]:
px.box(
    ammu.sort_values('Damage', ascending=True),
    x='Weapon Type',
    y='Damage',
    title='Damage Distribution by Weapon Type'
)

Highest damage is inflicted by Shotguns while pistols and submachine guns has the lowest damage.

In [24]:
px.box(
    ammu.sort_values('Damage', ascending=True),
    x='Bullet Type',
    y='Damage',
    points = 'all',
    hover_name= 'Weapon Name',
    title='Damage Distribution by Bullet Type'
)

12 Guage bullets (specially S686 and S1897) has higest damage while 9 mm has the lowest.

- Bullet speed

In [25]:
px.scatter(
    ammu.sort_values('Bullet Speed', ascending=True),
    x='Bullet Type',
    y='Bullet Speed',
    hover_name= 'Weapon Name',
    title='Bullet speed Distribution by Bullet Type'
)

.300 Magnum (single weapon AWM) and 5.55mm bullets has the higest average Bullet speed

- Range

In [26]:
px.scatter(
    ammu.sort_values('Range', ascending=True),
    x='Bullet Type',
    y='Range',
    hover_name= 'Weapon Name',
    title='Range Distribution by Bullet Type'
)

.300 Magnum (single weapon AWM) and 5.55mm bullets has the higest average  Range

- Magazine Capacity

In [27]:
px.scatter(
    ammu.sort_values('Magazine Capacity', ascending=True),
    x='Weapon Type',
    y='Magazine Capacity',
    hover_name= 'Weapon Name',
    title='Magazine Capacity among Weapon Types'
)

- Damage Per Second

In [28]:
px.scatter(
    ammu.sort_values('Damage Per Second', ascending=True),
    x='Weapon Name',
    y='Damage Per Second',
    #color= "Weapon Type",
    hover_name= 'Weapon Type',
    title='Damage Per Second among Weapon Types'
)

- Damage Per Second vs Rate of Fire

In [29]:
px.scatter(
    ammu,
    x='Rate of Fire',
    y='Damage Per Second',
    title='DPS vs Rate of Fire'
)

#### Bullet Speed vs Range

In [30]:
px.scatter(
    ammu,
    x='Bullet Speed',
    y='Range',
    color='Weapon Type',
    hover_name='Weapon Name',
    title='Ballistic Performance'
)

In [31]:
fig = px.scatter(
    ammu.sort_values('Damage_per_mag', ascending=True),
    y='Weapon Name',
    x='Damage_per_mag',
    hover_name='Weapon Type',
    title='Damage Output per Magazine'
)
fig.show()

Light machine guns has high magazine damage offering superior sustained engagement capability.

In [32]:
fig = make_subplots(
    rows=2, cols=2, 
    subplot_titles=("No Vest (Level 0)", "Level 1 Vest", "Level 2 Vest", "Level 3 Vest"),
    shared_yaxes=True 
)

#  i to row and col mapping: 0->(1,1), 1->(1,2), 2->(2,1), 3->(2,2)
for i in range(4):
    row = (i // 2) + 1
    col = (i % 2) + 1
    
    fig.add_trace(
        go.Bar(
            x=ammu['Weapon Name'],
            y=ammu[f'BDMG_{i}'].sort_values(),
            name=f'Level {i}',
            showlegend=False 
        ),
        row=row, col=col
    )

fig.update_layout(
    height=800, 
    width=1000, 
    title_text="Body Damage Comparison by Armor Level",
    template="plotly_white"
)

fig.update_xaxes(tickangle=45)

fig.show()

In [33]:
fig = make_subplots(
    rows=2, cols=2, 
    subplot_titles=("No Vest (Level 0)", "Level 1 Vest", "Level 2 Vest", "Level 3 Vest"),
    shared_yaxes=True 
)

#  i to row and col mapping: 0->(1,1), 1->(1,2), 2->(2,1), 3->(2,2)
for i in range(4):
    row = (i // 2) + 1
    col = (i % 2) + 1
    
    fig.add_trace(
        go.Bar(
            x=ammu['Weapon Name'],
            y=ammu[f'HDMG_{i}'].sort_values(),
            name=f'Level {i}',
            showlegend=False 
        ),
        row=row, col=col
    )

fig.update_layout(
    height=800, 
    width=1300, 
    title_text="Head Damage Comparison by Armor Level",
    template="plotly_white"
)

fig.update_xaxes(tickangle=45)

fig.show()

Skorpion and P18C has the higest damage regardless level of protection

Dashboard Sections:

In [34]:
import dash
from dash import dcc, html, Input, Output

In [35]:

# Initialize the Dash app
app = dash.Dash(__name__, external_stylesheets=['https://codepen.io/chriddyp/pen/bWLwgP.css'])

# APP LAYOUT
app.layout = html.Div([
    html.Div([
        html.H1("PUBG Weapon Analytics Dashboard", style={'textAlign': 'center', 'marginBottom': '20px'}),
        
        # Filters Section
        html.Div([
            html.Label("Filter by Weapon Type:"),
            dcc.Dropdown(
                id='weapon-type-filter',
                options=[{'label': i, 'value': i} for i in sorted(df['Weapon Type'].unique())],
                value=df['Weapon Type'].unique().tolist(),
                multi=True
            ),
        ], style={'padding': '20px', 'backgroundColor': '#f9f9f9', 'borderRadius': '5px', 'marginBottom': '20px'}),
    ], className="container"),

    #Tabs for different sections
    dcc.Tabs([
        # Tab 1: Overview
        dcc.Tab(label='1. Overview & Ranking', children=[
            html.Div([
                html.H3("Weapon Power Ranking (DPS)"),
                dcc.Graph(id='weapon-ranking-bar')
            ], style={'padding': '20px'})
        ]),

        # Tab 2: Combat Analysis
        dcc.Tab(label='2. Combat Analysis', children=[
            html.Div([
                html.H3("Lethality: DPS vs Time-To-Kill"),
                dcc.Graph(id='dps-ttk-scatter')
            ], style={'padding': '20px'})
        ]),

        # Tab 3: Ballistics
        dcc.Tab(label='3. Ballistics', children=[
            html.Div([
                html.H3("Ballistic Performance: Speed vs Range"),
                dcc.Graph(id='ballistics-scatter')
            ], style={'padding': '20px'})
        ]),

        # Tab 4: Efficiency
        dcc.Tab(label='4. Efficiency', children=[
            html.Div([
                html.H3("Damage Potential per Magazine"),
                dcc.Graph(id='mag-efficiency-bar')
            ], style={'padding': '20px'})
        ]),

        # Tab 5: Armour Analysis
        dcc.Tab(label='5. Armour Analysis', children=[
            html.Div([
                html.H3("Damage Reduction across Armour Levels"),
                dcc.RadioItems(
                    id='armour-type-selector',
                    options=[{'label': 'Body Damage', 'value': 'BDMG'}, {'label': 'Head Damage', 'value': 'HDMG'}],
                    value='BDMG',
                    labelStyle={'display': 'inline-block', 'marginRight': '20px'}
                ),
                dcc.Graph(id='armour-analysis-graph')
            ], style={'padding': '20px'})
        ]),
    ])
])

# CALLBACKS
@app.callback(
    [Output('weapon-ranking-bar', 'figure'),
     Output('dps-ttk-scatter', 'figure'),
     Output('ballistics-scatter', 'figure'),
     Output('mag-efficiency-bar', 'figure'),
     Output('armour-analysis-graph', 'figure')],
    [Input('weapon-type-filter', 'value'),
     Input('armour-type-selector', 'value')]
)
def update_dashboard(selected_types, armour_type):
    filtered_df = df[df['Weapon Type'].isin(selected_types)].sort_values('Damage Per Second', ascending=False)
    firearms_df = filtered_df[filtered_df['Weapon Class'] == 'Firearm']

    # Figure 1: Ranking
    fig_ranking = px.bar(
        filtered_df, x='Weapon Name', y='Damage Per Second',
        color='Weapon Type', title="Weapons Ranked by DPS"
    )

    # Figure 2: Combat Analysis
    y_col = 'TTK_chest'
    fig_combat = px.scatter(
        filtered_df, x='Damage Per Second', y='TTK_chest' if 'TTK_chest' in df.columns else 'Damage',
        color='Weapon Type', hover_name='Weapon Name',
        title="DPS vs Time-To-Kill (Lower TTK is better)",
        labels={'TTK_chest': 'Time to Kill (Chest)'}
    )
    if not filtered_df.empty:
        mean_x = filtered_df['Damage Per Second'].mean()
        mean_y = filtered_df[y_col].mean()

        # Add Crosshair Lines
        fig_combat.add_vline(x=mean_x, line_dash="dash", line_color="gray", opacity=0.5)
        fig_combat.add_hline(y=mean_y, line_dash="dash", line_color="gray", opacity=0.5)

        # Annotations (Positioned at corners relative to the data)
            # Bottom Right: High DPS, Low TTK
        fig_combat.add_annotation(x=filtered_df['Damage Per Second'].max(), y=filtered_df[y_col].min(),
                            text="<b>META MELTERS</b><br>High Power, Fast Kills", showarrow=False, 
                            yshift=15, xanchor='right', font=dict(color="green", size=10))

            # Bottom Left: Low DPS, Low TTK
        fig_combat.add_annotation(x=filtered_df['Damage Per Second'].min(), y=filtered_df[y_col].min(),
                            text="<b>PRECISION TOOLS</b><br>Efficient/Snipers", showarrow=False, 
                            yshift=15, xanchor='left', font=dict(color="blue", size=10))

            # Top Right: High DPS, High TTK
        fig_combat.add_annotation(x=filtered_df['Damage Per Second'].max(), y=filtered_df[y_col].max(),
                            text="<b>BULLET HOSES</b><br>High Pressure, Low Finish", showarrow=False, 
                            yshift=-15, xanchor='right', font=dict(color="orange", size=10))

            # Top Left: Low DPS, High TTK
        fig_combat.add_annotation(x=filtered_df['Damage Per Second'].min(), y=filtered_df[y_col].max(),
                            text="<b>HARASSERS</b><br>Low Lethality", showarrow=False, 
                            yshift=-15, xanchor='left', font=dict(color="red", size=10))
        


    # Figure 3: Ballistics
    fig_ballistics = px.scatter(
        firearms_df, x='Bullet Speed', y='Range',
        size='Damage', color='Weapon Type', hover_name='Weapon Name',
        title="Bullet Speed vs Effective Range"
    )

    # Figure 4: Efficiency
    fig_mag = px.bar(
        filtered_df.sort_values('Damage_per_mag', ascending=False),
        x='Weapon Name', y='Damage_per_mag', color='Bullet Type',
        title="Total Damage Output per Magazine"
    )

    # Figure 5: Armour Analysis (Subplots for Levels 0-3)
    fig_armour = make_subplots(rows=2, cols=2, subplot_titles=("Level 0", "Level 1", "Level 2", "Level 3"))
    for i in range(4):
        col_name = f'{armour_type}_{i}'
        r, c = (i // 2) + 1, (i % 2) + 1
        fig_armour.add_trace(
            go.Bar(x=filtered_df['Weapon Name'], y=firearms_df[col_name], name=f"Lvl {i}"),
            row=r, col=c
        )
    fig_armour.update_layout(height=700, title_text=f"{armour_type} Comparison by Protection Level", showlegend=False)

    return fig_ranking, fig_combat, fig_ballistics, fig_mag, fig_armour

# 4. RUN SERVER
if __name__ == '__main__':
    app.run(debug=True)

dashboard link (local): http://127.0.0.1:8050

In [37]:
!jupyter nbconvert --to html PUBG_EDA.ipynb

[NbConvertApp] Converting notebook PUBG_EDA.ipynb to html
[NbConvertApp] Writing 711267 bytes to PUBG_EDA.html